# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brokerage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BrokerageName', models.CharField(max_length=500)),
                ('ReviewLink', models.CharField(max_length=1000)),
                ('ContactLink', models.CharField(max_length=1000)),
                ('Location', models.CharField(max_length=500)),
                ('YearlyCosts', models.DecimalField(decimal_places=2, max_digits=12)),
                ('CommisionSplit', models.CharField(max_length=8)),
                ('Cap', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Marketing', models.CharField(max_length=500)),
                ('OfficeLeaders', models.CharField(max_length=500)),
            ],
        ),
    ]
