# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrokerageTable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokerage',
            name='ConferenceRooms',
            field=models.BooleanField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brokerage',
            name='Desks',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brokerage',
            name='Mentorship',
            field=models.BooleanField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brokerage',
            name='Onboarding',
            field=models.BooleanField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brokerage',
            name='Teams_Hiring',
            field=models.BooleanField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brokerage',
            name='TotalAgents',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brokerage',
            name='TotalListings',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brokerage',
            name='TrainingPerWeek',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
